apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app2
  namespace: argocd
spec:
  destination:
    namespace: helm-app2
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: helm-dependency
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master
    helm:
     releaseName: my-release2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
