apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: o11y
spec:
  destination:
    namespace: o11y
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: prometheus
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: HEAD
    helm:
      releaseName: prometheus
      # valuesFiles:
      #   - values-prd.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true