apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  destination:
    namespace: kubeseal
    server: "https://kubernetes.default.svc"
  sources:
    - chart: sealed-secrets
      repoURL: https://bitnami-labs.github.io/sealed-secrets
      targetRevision: 1.16.1
      helm:
        releaseName: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true