apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
  namespace: security
spec:
  destination:
    namespace: security
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - chart: trivy
      repoURL: "https://charts.softonic.io"
      # targetRevision: 52.1.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true