apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart for kube-prometheus-stack deployment
type: application
version: 52.1.0
appVersion: "v0.68.0"
dependencies:
  - name: kube-prometheus-stack
    version:  "52.1.0"
    repository:  "https://prometheus-community.github.io/helm-charts"
